// chat EVENTS
export const SOCKET_EVENTS = {
    USER_CONNECTED: 'USER_CONNECTED',
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGE_SENT: 'MESSAGE_SENT',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    TYPING: 'TYPING'
};
